### ISSUE TITLE
[documentation] CLI flag "-i" needs to be added to the readme

### ISSUE THREAD

**Issue by fun3md** [barasher/picdexer#14]
flag is not mentioned in the readme
very helpful when ingesting pictures from different machines and folders, use this as a unique key for later compares

**Comment by barasher** [comment]
Fix in commit b82c67b422ef43c4ea1c1772887d6065b5b8e781
Will be released in 2.0.0

**Comment by barasher** [comment]
https://github.com/barasher/picdexer/tree/v2.0.0
